# Generated by Django 5.0.3 on 2026-03-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2026)),
                (
                    "building_pledge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stewardship_pledge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "other_pledges",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("submission_date", models.DateField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "member__full_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="pledge",
            constraint=models.UniqueConstraint(
                fields=("tenant", "member", "year"),
                name="uniq_member_year_pledge_per_tenant",
            ),
        ),
    ]
