# Generated by Django 5.0.3 on 2026-03-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FellowshipGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("leader_name", models.CharField(max_length=200)),
                ("leader_phone", models.CharField(max_length=20)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FellowshipParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_leader", models.BooleanField(default=False)),
                ("joined_date", models.DateField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fellowships.fellowshipgroup",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.member"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["group__name", "member__full_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="fellowshipgroup",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="uniq_fellowship_name_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="fellowshipparticipation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "member", "group"),
                name="uniq_member_group_per_tenant",
            ),
        ),
    ]
