# Generated by Django 5.0.3 on 2026-03-09 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("membership_no", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("marital_status", models.CharField(max_length=20)),
                ("marriage_type", models.CharField(blank=True, max_length=50)),
                ("marriage_date", models.DateField(blank=True, null=True)),
                ("marriage_place", models.CharField(blank=True, max_length=200)),
                ("spouse_name", models.CharField(blank=True, max_length=200)),
                ("primary_phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("residence_area", models.CharField(max_length=100)),
                ("house_block_no", models.CharField(max_length=50)),
                ("previous_parish", models.CharField(blank=True, max_length=200)),
                ("elder_name", models.CharField(blank=True, max_length=200)),
                ("elder_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="SpiritualProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_baptized", models.BooleanField(default=False)),
                ("baptism_date", models.DateField(blank=True, null=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                ("takes_communion", models.BooleanField(default=False)),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("education_level", models.CharField(blank=True, max_length=50)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("work_place", models.CharField(blank=True, max_length=200)),
                ("volunteer_status", models.BooleanField(default=False)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spiritual_progress",
                        to="members.member",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["member__full_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("tenant", "membership_no"),
                name="uniq_member_membership_per_tenant",
            ),
        ),
    ]
