# Generated by Django 5.0.3 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_password_member_username_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="residence_area",
            new_name="residence_name",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="house_block_no",
            new_name="block_number",
        ),
        migrations.AddField(
            model_name="member",
            name="place_of_birth",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="living_with_spouse_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="dependents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="member",
            name="spouse_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="member",
            name="po_box",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="house_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="fellowship_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="neighbor_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="neighbor_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="member",
            name="occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="work_place",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="education_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="member",
            name="profession",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="volunteer_status",
            field=models.BooleanField(default=False),
        ),
    ]
