# Generated by Django 5.0.3 on 2026-03-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_member_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="is_baptized",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="baptism_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="confirmation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="participates_in_sacraments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="participates_in_fellowship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="fellowship_house_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="fellowship_non_participation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="fellowship_chairperson_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="fellowship_chairperson_signature",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="join_fellowship",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="join_sunday_school",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="join_visiting_sick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="join_bible_study",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="join_choir",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="join_union",
            field=models.BooleanField(default=False),
        ),
    ]
