# Generated by Django 5.0.3 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0004_member_additional_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="dependents",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
