# Generated by Django 5.0.3 on 2026-04-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_member_dependents_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("assigned_membership_no", models.CharField(blank=True, max_length=50)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("place_of_birth", models.CharField(blank=True, max_length=200)),
                ("marital_status", models.CharField(max_length=20)),
                ("marriage_type", models.CharField(blank=True, max_length=50)),
                ("marriage_date", models.DateField(blank=True, null=True)),
                ("marriage_place", models.CharField(blank=True, max_length=200)),
                ("spouse_name", models.CharField(blank=True, max_length=200)),
                (
                    "living_with_spouse_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "dependents",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("primary_phone", models.CharField(max_length=20)),
                ("spouse_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("po_box", models.CharField(blank=True, max_length=50)),
                ("house_number", models.CharField(blank=True, max_length=50)),
                ("residence_name", models.CharField(blank=True, max_length=100)),
                ("block_number", models.CharField(blank=True, max_length=50)),
                ("fellowship_name", models.CharField(blank=True, max_length=100)),
                ("previous_parish", models.CharField(blank=True, max_length=200)),
                ("neighbor_name", models.CharField(blank=True, max_length=200)),
                ("neighbor_phone", models.CharField(blank=True, max_length=20)),
                ("elder_name", models.CharField(blank=True, max_length=200)),
                ("elder_phone", models.CharField(blank=True, max_length=20)),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("work_place", models.CharField(blank=True, max_length=200)),
                ("education_level", models.CharField(blank=True, max_length=50)),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("volunteer_status", models.BooleanField(default=False)),
                ("is_baptized", models.BooleanField(default=False)),
                ("baptism_date", models.DateField(blank=True, null=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                ("participates_in_sacraments", models.BooleanField(default=False)),
                ("participates_in_fellowship", models.BooleanField(default=False)),
                (
                    "fellowship_house_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "fellowship_non_participation_reason",
                    models.TextField(blank=True),
                ),
                (
                    "fellowship_chairperson_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "fellowship_chairperson_signature",
                    models.CharField(blank=True, max_length=200),
                ),
                ("join_fellowship", models.BooleanField(default=False)),
                ("join_sunday_school", models.BooleanField(default=False)),
                ("join_visiting_sick", models.BooleanField(default=False)),
                ("join_bible_study", models.BooleanField(default=False)),
                ("join_choir", models.BooleanField(default=False)),
                ("join_union", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_member_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_records",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
