# Generated by Django 5.0.3 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0007_fix_user_fk_delete_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberapplication",
            name="has_membership_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="membership_registration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="membership_registered_full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="pledge_building",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="pledge_other",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="pledge_stewardship",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="memberapplication",
            name="pledge_year",
            field=models.IntegerField(default=0),
        ),
    ]
